# This is a basic workflow to help you get started with Actions

name: Deploy To Maven

# Controls when the action will run. 
on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Set version env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Append variables
        run: |
          echo "\n" >> gradle.properties
          echo "publicationVersionName=$RELEASE_VERSION" >> gradle.properties
          echo "ossrh.username=$OOSRH_USERNAME" >> gradle.properties
          echo "ossrh.password=$OOSRH_PASSWORD" >> gradle.properties
          echo "signing.keyId=$SIGNING_KEY_ID" >> gradle.properties
          echo "signing.password=$SIGNING_PASSWORD" >> gradle.properties
          echo "signing.secretKeyRingFile=$SIGNING_SECRET_RING" >> gradle.properties
        env:
          OOSRH_USERNAME: ${{ secrets.OOSRH_USERNAME }}
          OOSRH_PASSWORD: ${{ secrets.OOSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_RING: ${{ secrets.SIGNING_SECRET_RING }}
      - name: Create secring.gpg file
        run: |
          mkdir -p $SIGNING_SECRET_RING
          rmdir $SIGNING_SECRET_RING
          printf "$SIGNING_SECRET_RING_FILE" | base64 --decode > $SIGNING_SECRET_RING
        env:
          SIGNING_SECRET_RING: ${{ secrets.SIGNING_SECRET_RING }}
          SIGNING_SECRET_RING_FILE: ${{ secrets.SIGNING_SECRET_RING_FILE }}
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - run: ./gradlew assembleRelease publish
