# This is a basic workflow to help you get started with Actions

name: Deploy To Bintray

# Controls when the action will run. 
on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Set version env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Append version
        run: echo "publicationVersionName=$RELEASE_VERSION" >> gradle.properties
      - name: Create secring.gpg file
        run: |
          mkdir -p $SIGNING_SECRET_RING
          rmdir $SIGNING_SECRET_RING
          printf "$SIGNING_SECRET_RING_FILE" | base64 --decode > $SIGNING_SECRET_RING
        env:
          SIGNING_SECRET_RING: ${{ secrets.SIGNING_SECRET_RING }}
          SIGNING_SECRET_RING_FILE: ${{ secrets.SIGNING_SECRET_RING_FILE }}
      - name: Gradle Android
        # You may pin to the exact commit or the version.
        # uses: Raul6469/android-gradle-action@b8fc7c7bde2562a4578b7e1bd996cc78d841638e
        uses: Raul6469/android-gradle-action@2.0.0
        env:
          OOSRH_USERNAME: ${{ secrets.OOSRH_USERNAME }}
          OOSRH_PASSWORD: ${{ secrets.OOSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_RING: ${{ secrets.SIGNING_SECRET_RING }}
        with:
          # The ./gradlew command arguments
          script: assembleRelease publish
